export const columns = [
   { name: 'STUDENT NAME', uid: 'name' },
   { name: 'AGE', uid: 'age' },
   { name: 'GRADE/SECTION', uid: 'gradeSection' },
   { name: 'RETURN DATE', uid: 'returnDate' },
   { name: 'BOOK', uid: 'book' },
   { name: 'STATUS', uid: 'status' },
   { name: 'ACTIONS', uid: 'actions' },
];

export const users = [
   {
      id: 1,
      name: 'John Smith',
      age: 13,
      gradeSection: '7/A',
      duration: '2 weeks',
      book: 'The Catcher in the Rye',
      status: 'active',
   },
   {
      id: 2,
      name: 'Emma Johnson',
      age: 14,
      gradeSection: '8/B',
      duration: '1 week',
      book: 'To Kill a Mockingbird',
      status: 'active',
   },
   {
      id: 3,
      name: 'Michael Williams',
      age: 16,
      gradeSection: '10/C',
      duration: '3 days',
      book: '1984',
      status: 'active',
   },
   {
      id: 4,
      name: 'Sophia Brown',
      age: 17,
      gradeSection: '11/D',
      duration: '4 weeks',
      book: 'Brave New World',
      status: 'inactive',
   },
   {
      id: 5,
      name: 'Liam Davis',
      age: 15,
      gradeSection: '9/E',
      duration: '2 weeks',
      book: 'Fahrenheit 451',
      status: 'active',
   },
   {
      id: 6,
      name: 'Olivia Martinez',
      age: 14,
      gradeSection: '8/F',
      duration: '5 days',
      book: 'The Great Gatsby',
      status: 'inactive',
   },
   {
      id: 7,
      name: 'Noah Wilson',
      age: 13,
      gradeSection: '7/G',
      duration: '1 month',
      book: 'Lord of the Flies',
      status: 'active',
   },
   {
      id: 8,
      name: 'Ava Moore',
      age: 16,
      gradeSection: '10/H',
      duration: '2 weeks',
      book: 'Moby-Dick',
      status: 'inactive',
   },
   {
      id: 9,
      name: 'Isabella Taylor',
      age: 15,
      gradeSection: '9/I',
      duration: '1 week',
      book: 'Pride and Prejudice',
      status: 'active',
   },
   {
      id: 10,
      name: 'Mason Anderson',
      age: 17,
      gradeSection: '11/J',
      duration: '3 weeks',
      book: 'The Odyssey',
      status: 'active',
   },
];
